### ISSUE TITLE
Java sparkplug dataset - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ubunturtu** [eclipse/tahu#136]
I just used the source code as-is and everything works except the dataset metric. If I comment it out the code works fine.
Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: 'com.google.protobuf.Internal$IntList org.eclipse.tahu.protobuf.SparkplugBProto$Payload$DataSet.emptyIntList()'
        at org.eclipse.tahu.protobuf.SparkplugBProto$Payload$DataSet.<init>(SparkplugBProto.java:4913)
        at org.eclipse.tahu.protobuf.SparkplugBProto$Payload$DataSet.<clinit>(SparkplugBProto.java:8907)
        at org.eclipse.tahu.message.SparkplugBPayloadEncoder.setMetricValue(SparkplugBPayloadEncoder.java:347)
        at org.eclipse.tahu.message.SparkplugBPayloadEncoder.convertMetric(SparkplugBPayloadEncoder.java:97)
        at org.eclipse.tahu.message.SparkplugBPayloadEncoder.getBytes(SparkplugBPayloadEncoder.java:75)
        at com.iotech.spnode$Publisher.run(spnode.java:554)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by wes-johnson** [comment]
This has since been resolved.
