### ISSUE TITLE
UDT Example Exception

### ISSUE THREAD

**Issue by bryce-nakatani** [eclipse/tahu#214]
When running the Java "Sparkplug B UDT Example" in the 0.5.17 tag, an exception is thrown. This was ran on a Java 8 platform.

seq: 0
Publishing Edge Node Birth
seq: 1
Publishing Device Birth
09:14:41.261 [pool-1-thread-1] ERROR org.eclipse.tahu.message.SparkplugBPayloadEncoder - Failed to add metric: simpleType
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "9655074991080998347"
at org.eclipse.tahu.message.SparkplugBPayloadEncoder.getBytes(SparkplugBPayloadEncoder.java:81)
at org.eclipse.tahu.SparkplugExample$Publisher.run(SparkplugExample.java:358)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NumberFormatException: For input string: "9655074991080998347"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Long.parseLong(Long.java:692)
at java.base/java.lang.Long.parseLong(Long.java:817)
at org.eclipse.tahu.message.SparkplugBPayloadEncoder.setMetricValue(SparkplugBPayloadEncoder.java:352)
at org.eclipse.tahu.message.SparkplugBPayloadEncoder.convertMetric(SparkplugBPayloadEncoder.java:100)
at org.eclipse.tahu.message.SparkplugBPayloadEncoder.setMetricValue(SparkplugBPayloadEncoder.java:432)
at org.eclipse.tahu.message.SparkplugBPayloadEncoder.convertMetric(SparkplugBPayloadEncoder.java:100)
at org.eclipse.tahu.message.SparkplugBPayloadEncoder.getBytes(SparkplugBPayloadEncoder.java:78)
... 4 more

**Comment by wes-johnson** [comment]
This has been fixed.
